apiVersion: v1
kind: Service
metadata:
  name: news-aggregator-service
spec:
  selector:
    app: news-aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
